<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-26 17:00
=======
# Generated by Django 5.2.8 on 2025-11-22 07:04
>>>>>>> fffbd8bc80147b58f7f8f92c4bec209c333bfdb3

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
